<% secrets_enabled = ENV['AUTO_DEVOPS_BUILD_IMAGE_FORWARDED_CI_VARIABLES']&.length.to_i > 0 -%>
<% if secrets_enabled -%>
# syntax = docker/dockerfile:experimental
<% end -%>
FROM gliderlabs/herokuish as builder
COPY . /tmp/app
ARG BUILDPACK_URL
ENV USER=herokuishuser
<% if secrets_enabled -%>
RUN --mount=type=secret,id=auto-devops-build-secrets . /run/secrets/auto-devops-build-secrets && /bin/herokuish buildpack build
<% else -%>
RUN /bin/herokuish buildpack build
<% end -%>

FROM gliderlabs/herokuish
COPY --chown=herokuishuser:herokuishuser --from=builder /app /app
ENV PORT=5000
ENV USER=herokuishuser
EXPOSE 5000
CMD ["/bin/herokuish", "procfile", "start", "web"]
