#!/usr/bin/env ruby

# frozen_string_literal: true

require 'shellwords'

# Export environment variables in AUTO_DEVOPS_BUILD_IMAGE_FORWARDED_CI_VARIABLES
class BuildSecrets
  def initialize(env)
    @env = env
  end

  def variable_names
    @env['AUTO_DEVOPS_BUILD_IMAGE_FORWARDED_CI_VARIABLES']
      .to_s
      .split(',')
      .select { |var| @env.key?(var) }
  end

  def export_string
    variable_names.map do |var|
      value = @env[var]
      escaped_value = value.shellescape
      "export #{var}=#{escaped_value}"
    end.join("\n")
  end

  def self.run
    puts BuildSecrets.new(ENV).export_string
  end
end

BuildSecrets.run if $PROGRAM_NAME == __FILE__
